// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: us/jeffevans/testdata/sensor-reading.proto

// Protobuf Java Version: 3.25.2
package us.jeffevans.kc_repl.testdata;

public final class SensorReadingOuterClass {
  private SensorReadingOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SensorReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:us.jeffevans.kc_repl.testdata.SensorReading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 deviceId = 1;</code>
     * @return Whether the deviceId field is set.
     */
    boolean hasDeviceId();
    /**
     * <code>required uint64 deviceId = 1;</code>
     * @return The deviceId.
     */
    long getDeviceId();

    /**
     * <code>required double reading = 2;</code>
     * @return Whether the reading field is set.
     */
    boolean hasReading();
    /**
     * <code>required double reading = 2;</code>
     * @return The reading.
     */
    double getReading();

    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
  }
  /**
   * Protobuf type {@code us.jeffevans.kc_repl.testdata.SensorReading}
   */
  public static final class SensorReading extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:us.jeffevans.kc_repl.testdata.SensorReading)
      SensorReadingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SensorReading.newBuilder() to construct.
    private SensorReading(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SensorReading() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SensorReading();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.internal_static_us_jeffevans_kc_repl_testdata_SensorReading_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.internal_static_us_jeffevans_kc_repl_testdata_SensorReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.class, us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.Builder.class);
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private long deviceId_ = 0L;
    /**
     * <code>required uint64 deviceId = 1;</code>
     * @return Whether the deviceId field is set.
     */
    @java.lang.Override
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required uint64 deviceId = 1;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public long getDeviceId() {
      return deviceId_;
    }

    public static final int READING_FIELD_NUMBER = 2;
    private double reading_ = 0D;
    /**
     * <code>required double reading = 2;</code>
     * @return Whether the reading field is set.
     */
    @java.lang.Override
    public boolean hasReading() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double reading = 2;</code>
     * @return The reading.
     */
    @java.lang.Override
    public double getReading() {
      return reading_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReading()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, reading_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getTimestamp());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, deviceId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, reading_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTimestamp());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading)) {
        return super.equals(obj);
      }
      us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading other = (us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading) obj;

      if (hasDeviceId() != other.hasDeviceId()) return false;
      if (hasDeviceId()) {
        if (getDeviceId()
            != other.getDeviceId()) return false;
      }
      if (hasReading() != other.hasReading()) return false;
      if (hasReading()) {
        if (java.lang.Double.doubleToLongBits(getReading())
            != java.lang.Double.doubleToLongBits(
                other.getReading())) return false;
      }
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDeviceId()) {
        hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getDeviceId());
      }
      if (hasReading()) {
        hash = (37 * hash) + READING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getReading()));
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code us.jeffevans.kc_repl.testdata.SensorReading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:us.jeffevans.kc_repl.testdata.SensorReading)
        us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.internal_static_us_jeffevans_kc_repl_testdata_SensorReading_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.internal_static_us_jeffevans_kc_repl_testdata_SensorReading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.class, us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.Builder.class);
      }

      // Construct using us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimestampFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deviceId_ = 0L;
        reading_ = 0D;
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.internal_static_us_jeffevans_kc_repl_testdata_SensorReading_descriptor;
      }

      @java.lang.Override
      public us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading getDefaultInstanceForType() {
        return us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.getDefaultInstance();
      }

      @java.lang.Override
      public us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading build() {
        us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading buildPartial() {
        us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading result = new us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deviceId_ = deviceId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.reading_ = reading_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestampBuilder_ == null
              ? timestamp_
              : timestampBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading) {
          return mergeFrom((us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading other) {
        if (other == us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasReading()) {
          setReading(other.getReading());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          return false;
        }
        if (!hasReading()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                deviceId_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                reading_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 26: {
                input.readMessage(
                    getTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long deviceId_ ;
      /**
       * <code>required uint64 deviceId = 1;</code>
       * @return Whether the deviceId field is set.
       */
      @java.lang.Override
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required uint64 deviceId = 1;</code>
       * @return The deviceId.
       */
      @java.lang.Override
      public long getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>required uint64 deviceId = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(long value) {

        deviceId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 deviceId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0L;
        onChanged();
        return this;
      }

      private double reading_ ;
      /**
       * <code>required double reading = 2;</code>
       * @return Whether the reading field is set.
       */
      @java.lang.Override
      public boolean hasReading() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double reading = 2;</code>
       * @return The reading.
       */
      @java.lang.Override
      public double getReading() {
        return reading_;
      }
      /**
       * <code>required double reading = 2;</code>
       * @param value The reading to set.
       * @return This builder for chaining.
       */
      public Builder setReading(double value) {

        reading_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required double reading = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReading() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reading_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            timestamp_ != null &&
            timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimestampBuilder().mergeFrom(value);
          } else {
            timestamp_ = value;
          }
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        if (timestamp_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>optional .google.protobuf.Timestamp timestamp = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:us.jeffevans.kc_repl.testdata.SensorReading)
    }

    // @@protoc_insertion_point(class_scope:us.jeffevans.kc_repl.testdata.SensorReading)
    private static final us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading();
    }

    public static us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SensorReading>
        PARSER = new com.google.protobuf.AbstractParser<SensorReading>() {
      @java.lang.Override
      public SensorReading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SensorReading> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SensorReading> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public us.jeffevans.kc_repl.testdata.SensorReadingOuterClass.SensorReading getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_us_jeffevans_kc_repl_testdata_SensorReading_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_us_jeffevans_kc_repl_testdata_SensorReading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*us/jeffevans/testdata/sensor-reading.p" +
      "roto\022\035us.jeffevans.kc_repl.testdata\032\037goo" +
      "gle/protobuf/timestamp.proto\"a\n\rSensorRe" +
      "ading\022\020\n\010deviceId\030\001 \002(\004\022\017\n\007reading\030\002 \002(\001" +
      "\022-\n\ttimestamp\030\003 \001(\0132\032.google.protobuf.Ti" +
      "mestamp"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_us_jeffevans_kc_repl_testdata_SensorReading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_us_jeffevans_kc_repl_testdata_SensorReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_us_jeffevans_kc_repl_testdata_SensorReading_descriptor,
        new java.lang.String[] { "DeviceId", "Reading", "Timestamp", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
